# Dependencies
markdown:         redcarpet
highlighter:      true

# Permalinks
permalink:        :title

# Setup
title:            Teckos
tagline:          Blog de l'équipe technique de Xotelia
url:              http://xotelia.github.io
paginate:         5
baseurl:          /

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/xotelia/xotelia.github.io
