# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        :title

# Setup
title:            Techos
tagline:          Blog technique de Xotelia
url:              http://techos.xotelia.com
paginate:         5
baseurl:          /

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/xotelia/xotelia.github.io
